# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS = -m32

# Compile the strdup.
strdup : strdup.cc
	$(CPP) $(CPPFLAGS) -o strdup strdup.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f strdup
