# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS =

# Compile the factorial.
factorial : factorial.cc
	$(CPP) $(CPPFLAGS) -o factorial factorial.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f factorial
