# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS =

# Compile the lexical.
lexical : lexical.cc
	$(CPP) $(CPPFLAGS) -o lexical lexical.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f lexical
