# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS = -m32

# Compile the value.
value : value.cc
	$(CPP) $(CPPFLAGS) -o value value.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f value
