# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS  =

# Compile the mainloop.
mainloop : mainloop.cc
	$(CPP) $(CPPFLAGS) -o mainloop mainloop.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f mainloop
