# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS =

# Compile the singleton.
singleton : singleton.cc
	$(CPP) $(CPPFLAGS) -o singleton singleton.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f singleton
