# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS = -m64

# Compile the otest.
otest : otest.cc
	$(CPP) $(CPPFLAGS) -o otest otest.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f otest
