# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS =

# Compile the class_template.
class_template : class_template.cc
	$(CPP) $(CPPFLAGS) -o class_template class_template.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f class_template
