# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS  = -std=c++11

# Compile the auto.
auto : auto.cc
	$(CPP) $(CPPFLAGS) -o auto auto.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f auto
