# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS = -m64

# Compile the template.
template : template.cc
	$(CPP) $(CPPFLAGS) -o template template.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f template
