# Generic C++ Makefile

CPP = g++
CPPFLAGS = -Wall
LDFLAGS = -m32

# Compile the vectors.
vectors : vectors.cc
	$(CPP) $(CPPFLAGS) -o vectors vectors.cc $(LDFLAGS)

# command to be executed.
clean:
	rm -f vectors
